default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch('DB_NAME',     'webapp') %>
  username: <%= ENV.fetch('DB_USERNAME', 'webapp')  %>
  password: <%= ENV.fetch('DB_PASSWORD', 'webapp')  %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-app-starting-template_development

test:
  <<: *default
  database: rails-app-starting-template_test

production:
  adapter: postgresql
  encoding: unicode
  pool:     50
  timeout:  5000
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     localhost
  port:     5432
